# 架构定义
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := cortex-a55

# 引导和内核（必须使用你提取的内核）
TARGET_NO_BOOTLOADER := true
TARGET_NO_KERNEL := false
TARGET_PREBUILT_KERNEL := device/unisoc/ums312/kernel
BOARD_KERNEL_CMDLINE := console=ttyS1,115200n8 androidboot.selinux=permissive
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x01000000
BOARD_TAGS_OFFSET := 0x00000100

# 分区大小（基于你提供的分区表精确计算，单位：字节）
BOARD_BOOTIMAGE_PARTITION_SIZE := 36700160      # mmcblk0p24: 35MB
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 41943040  # mmcblk0p3: 40MB
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 5368709120  # mmcblk0p27: 5GB
BOARD_USERDATAIMAGE_PARTITION_SIZE := 25079951360 # mmcblk0p33: ~23.3GB
BOARD_VENDORIMAGE_PARTITION_SIZE := 419430400   # mmcblk0p29: 400MB
BOARD_FLASH_BLOCK_SIZE := 4096

# Android 9 系统特性
BOARD_BUILD_SYSTEM_ROOT_IMAGE := true
AB_OTA_UPDATER := false  # 根据分区表，判断你的设备不是A/B分区

# TWRP 通用配置
TW_THEME := portrait_hdpi
TW_SCREEN_BLANK_ON_BOOT := true
TW_MAX_BRIGHTNESS := 255
TW_DEFAULT_BRIGHTNESS := 128
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_USE_TOOLBOX := true
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_HAS_DOWNLOAD_MODE := true
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
TARGET_USES_LOGD := true

# 【关键】加密配置：确认你的fstab无forceencrypt标志，故关闭加密支持
TW_INCLUDE_CRYPTO := false
TW_INCLUDE_FBE := false

# Goodix触摸屏特殊配置（基于你的getevent信息）
TW_IGNORE_ABS_MT_TRACKING_ID := true
RECOVERY_TOUCHSCREEN_SWAP_XY := true
RECOVERY_TOUCHSCREEN_FLIP_Y := true

# 其他
TW_EXCLUDE_APEX := true
TW_EXTRA_LANGUAGES := true
TW_INCLUDE_RESETPROP := true
TW_USE_SERIALNO_PROPERTY_FOR_DEVICE_ID := true
